import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { parseWxr } from "../src/core.js";
import { generateAstroProject } from "../src/generate.js";
import { redirectRuleFiles } from "../src/redirect-rules.js";
import type { MigrationProject } from "../src/types.js";
import { demoFixturePath } from "./fixture-path.js";

const rulePaths = [
  "migration/redirect-rules/netlify/_redirects",
  "migration/redirect-rules/vercel/vercel.json",
  "migration/redirect-rules/nginx/redirects.conf",
  "migration/redirect-rules/apache/.htaccess"
];

function publishedPage(postId: string, link: string): string {
  return [
    "<item>",
    `<title>Page ${postId}</title>`,
    `<link>${link}</link>`,
    `<wp:post_id>${postId}</wp:post_id>`,
    "<wp:post_type>page</wp:post_type>",
    "<wp:status>publish</wp:status>",
    `<wp:post_name>page-${postId}</wp:post_name>`,
    "</item>"
  ].join("");
}

function wxrDocument(...items: readonly string[]): string {
  return [
    '<rss version="2.0" xmlns:wp="http://wordpress.org/export/1.2/">',
    "<channel>",
    "<title>Example site</title>",
    "<link>https://example.test/</link>",
    ...items,
    "</channel></rss>"
  ].join("");
}

function fileContents(files: readonly { readonly path: string; readonly contents: string }[], path: string): string {
  const file = files.find((candidate) => candidate.path === path);
  assert.ok(file, `missing generated rule file: ${path}`);
  return file.contents;
}

test("writes one rule file per host from the same redirect map", async () => {
  const project = parseWxr(await readFile(demoFixturePath, "utf8"));
  assert.equal(project.routes.redirects.length, 1, "the demo needs exactly one rule");

  const files = redirectRuleFiles(project);
  assert.deepEqual(files.map((file) => file.path), rulePaths);

  const netlify = fileContents(files, rulePaths[0]!);
  assert.match(netlify, /^# Generated by wp-migrate-core \d+\.\d+\.\d+ from the WordPress export\.$/m);
  assert.match(netlify, /^# 1 rule, matching the redirect map in migration\/redirects\.json\.$/m);
  assert.match(netlify, /^# Handled by Pretty URLs: \/guides\/stop-a-leaking-tap -> \/guides\/stop-a-leaking-tap\/$/m);
  assert.doesNotMatch(netlify, /^\//m, "Netlify slash-only rules would match their own destination");

  const nginx = fileContents(files, rulePaths[2]!);
  assert.ok(nginx.includes('if ($request_uri ~ "^/guides/stop-a-leaking-tap(?:[?].*)?$") {'));
  assert.ok(nginx.includes('return 301 "/guides/stop-a-leaking-tap/$is_args$args";'));

  const apache = fileContents(files, rulePaths[3]!);
  assert.ok(apache.includes('RewriteRule ^ "/guides/stop-a-leaking-tap/" [R=301,L,NE]'));

  const vercel = JSON.parse(fileContents(files, rulePaths[1]!));
  assert.deepEqual(vercel, {
    redirects: [{ source: "/(guides/stop-a-leaking-tap$)", destination: "/guides/stop-a-leaking-tap/", statusCode: 301 }]
  });

});

test("escapes paths a rules file cannot carry literally", () => {
  // A permalink with a space, parentheses, a stray percent sign and a dollar
  // sign: everything a host configuration would misread if it were written out.
  const project = parseWxr(wxrDocument(publishedPage("1", "https://example.test/report (final)/100%/cost$")));
  assert.deepEqual(
    project.routes.redirects.map((redirect) => [redirect.sourcePath, redirect.targetRoute]),
    [["/report%20(final)/100%/cost$", "/report%20(final)/100%/cost$/"]]
  );

  const files = redirectRuleFiles(project);
  const netlify = fileContents(files, rulePaths[0]!);
  assert.match(netlify, /# Handled by Pretty URLs: \/report%20\(final\)\/100%25\/cost\$/);
  for (const line of netlify.split("\n")) {
    assert.doesNotMatch(line, /%(?![0-9A-Fa-f]{2})/, `unescaped percent sign in: ${line}`);
  }

  const apache = fileContents(files, rulePaths[3]!);
  assert.ok(
    apache.includes(String.raw`RewriteRule ^ "/report\%20(final)/100\%25/cost\%24/" [R=301,L,NE]`),
    apache
  );
});

test("Apache conditions match original paths exactly, including encoded separators and query suffixes", () => {
  const project = parseWxr(wxrDocument());
  const files = redirectRuleFiles({ ...project, routes: { ...project.routes, redirects: [{
    id: "encoded", sourcePath: "/old%2Fpath/(final)/cost$1", targetRoute: "/new/", reason: "Moved"
  }] } });
  const apache = fileContents(files, rulePaths[3]!);
  const condition = /^RewriteCond %\{THE_REQUEST\} "(.+)"$/m.exec(apache)?.[1];
  assert.ok(condition);
  const pattern = new RegExp(condition);
  assert.match("GET /old%2Fpath/(final)/cost$1 HTTP/1.1", pattern);
  assert.match("GET /old%2Fpath/(final)/cost$1?next=1 HTTP/1.1", pattern);
  assert.doesNotMatch("GET /old/path/(final)/cost$1 HTTP/1.1", pattern);
  assert.doesNotMatch("GET /old%2Fpath/(final)/cost$1/ HTTP/1.1", pattern);
});

test("escapes platform pattern syntax and keeps Unicode and config delimiters intact", () => {
  const project = parseWxr(wxrDocument());
  const files = redirectRuleFiles({ ...project, routes: { ...project.routes, redirects: [{
    id: "special", sourcePath: "/old/:name/(final)/*/café/😀/a;b/cost$1", targetRoute: "/new/:literal/😀/cost$1/", reason: "Moved"
  }] } });
  const netlify = fileContents(files, rulePaths[0]!);
  assert.match(netlify, /\/old\/%3Aname\/\(final\)\/%2A\/caf%C3%A9\/%F0%9F%98%80/);
  const vercel = JSON.parse(fileContents(files, rulePaths[1]!));
  assert.equal(vercel.redirects[0].source, String.raw`/(old/:name/\(final\)/\*/caf%C3%A9/%F0%9F%98%80/a;b/cost\$1$)`);
  assert.equal(vercel.redirects[0].destination, "/new/%3Aliteral/%F0%9F%98%80/cost%241/");
  const nginx = fileContents(files, rulePaths[2]!);
  assert.ok(nginx.includes('return 301 "/new/:literal/%F0%9F%98%80/cost%241/$is_args$args";'));
  assert.doesNotMatch(files.map((file) => file.contents).join(""), /%EF%BF%BD/);
});

test("Vercel literal patterns cannot match their own trailing-slash destinations", () => {
  const project = parseWxr(wxrDocument(publishedPage("1", "https://example.test/file.html")));
  const vercel = JSON.parse(fileContents(redirectRuleFiles(project), rulePaths[1]!));
  const rule = vercel.redirects[0];
  // Model the optional trailing slash that Vercel adds outside a source pattern.
  const matcher = new RegExp(`^${rule.source}(?:/)?$`);
  assert.match("/file.html", matcher);
  assert.doesNotMatch(rule.destination, matcher);
  assert.doesNotMatch("/fileXhtml", matcher);
});

test("does not write off-site, query-bearing, fragment-bearing or self redirects from library input", () => {
  const project = parseWxr(wxrDocument());
  const redirects = [
    ["/old", "//external.test/new"], ["/old", "/\\external.test/new"],
    ["/old?private=secret", "/new/"], ["/old#private", "/new/"], ["/same/", "/same/"]
  ].map(([sourcePath, targetRoute], index) => ({ id: String(index), sourcePath: sourcePath!, targetRoute: targetRoute!, reason: "Moved" }));
  assert.deepEqual(redirectRuleFiles({ ...project, routes: { ...project.routes, redirects } }), []);
});

test("writes no rule file when the plan needs no redirect", () => {
  const project = parseWxr(wxrDocument(publishedPage("1", "https://example.test/example-page/")));

  assert.equal(project.routes.redirects.length, 0);
  assert.deepEqual(redirectRuleFiles(project), []);
});

test("ships the coverage inventory and the rule files with the generated project", async (context) => {
  const output = await mkdtemp(join(tmpdir(), "wp-migrate-core-rules-"));
  context.after(() => rm(output, { recursive: true, force: true }));

  const xml = wxrDocument(publishedPage("1", "https://example.test/example-page"));
  const project: MigrationProject = parseWxr(xml, {
    liveUrlSource: {
      urls: ["https://example.test/example-page", "https://example.test/example-page/", "https://example.test/gone/"],
      sitemapRefs: []
    }
  });
  await generateAstroProject(project, output);

  const coverage = JSON.parse(await readFile(join(output, "migration", "coverage.json"), "utf8"));
  assert.equal(coverage.schemaVersion, "0.4");
  assert.equal(coverage.summary.checked, true);
  assert.deepEqual(coverage.summary, project.coverage.summary);

  const manifest = JSON.parse(await readFile(join(output, "migration", "manifest.json"), "utf8"));
  assert.equal(manifest.schemaVersion, "0.4");
  assert.equal(manifest.coverage.file, "migration/coverage.json");
  assert.deepEqual(manifest.coverage.summary, coverage.summary);

  for (const path of rulePaths) {
    assert.ok((await readFile(join(output, path), "utf8")).length > 0, path);
  }

  const readme = await readFile(join(output, "README.md"), "utf8");
  assert.match(readme, /migration\/coverage\.json/);
  assert.match(readme, /migration\/redirect-rules\//);
  assert.match(readme, /1 with no route or rule/);
});

test("explains an unchecked coverage run in the generated handoff", async (context) => {
  const output = await mkdtemp(join(tmpdir(), "wp-migrate-core-rules-unchecked-"));
  context.after(() => rm(output, { recursive: true, force: true }));

  const project = parseWxr(wxrDocument(publishedPage("1", "https://example.test/example-page/")));
  await generateAstroProject(project, output);

  const coverage = JSON.parse(await readFile(join(output, "migration", "coverage.json"), "utf8"));
  assert.equal(coverage.summary.checked, false);
  assert.deepEqual(coverage.entries, []);

  const readme = await readFile(join(output, "README.md"), "utf8");
  assert.match(readme, /No live URL source was supplied/);
  assert.match(readme, /This plan needs no path rule, so no rule files were written\./);
});
