import type { MigrationProject, RedirectEntry } from "./types.js";
import { packageVersion } from "./version.js";

/**
 * Redirect rules for the hosts a migrated WordPress site usually moves to.
 *
 * These files are a handoff, not a deployment: nothing here is uploaded, and
 * every rule still has to be reviewed and published by a human. The rules come
 * from the redirect map the report shows, with host-specific normalization
 * called out where a platform handles a proposed rule itself.
 */
export interface RedirectRuleFile {
  /** Path relative to the generated project root. */
  readonly path: string;
  readonly contents: string;
}

export function redirectRuleFiles(project: MigrationProject): RedirectRuleFile[] {
  const rules = safeRedirectRules(project.routes.redirects);
  if (rules.length === 0) {
    // An empty rules file would look like a working configuration and say
    // nothing. The report and the redirect inventory carry the explanation.
    return [];
  }

  return [
    { path: "migration/redirect-rules/netlify/_redirects", contents: renderNetlifyRedirects(project) },
    { path: "migration/redirect-rules/vercel/vercel.json", contents: renderVercelRedirects(project) },
    { path: "migration/redirect-rules/nginx/redirects.conf", contents: renderNginxRedirects(project) },
    { path: "migration/redirect-rules/apache/.htaccess", contents: renderApacheRedirects(project) }
  ];
}

/** Netlify `_redirects`: `<from> <to> <status>` per line. */
export function renderNetlifyRedirects(project: MigrationProject): string {
  const rules = safeRedirectRules(project.routes.redirects);
  return [
    ...ruleHeader(rules),
    "# Copy this file into the publish directory as _redirects.",
    "# Netlify normalizes trailing slashes before matching. Enable Pretty URLs",
    "# for slash-only changes; emitting those as redirects can cause loops.",
    ...rules.map((rule) => slashOnly(rule)
      ? `# Handled by Pretty URLs: ${rulePath(rule.sourcePath)} -> ${rulePath(rule.targetRoute)}`
      : `${netlifyPath(rule.sourcePath)} ${netlifyPath(rule.targetRoute)} 301`)
  ].join("\n") + "\n";
}

/** Vercel `vercel.json`. The format is strict JSON, so it carries no comments. */
export function renderVercelRedirects(project: MigrationProject): string {
  const rules = safeRedirectRules(project.routes.redirects);
  return `${JSON.stringify({
    redirects: rules.map((rule) => ({
      // An end anchor inside the pattern prevents Vercel's optional trailing
      // slash from also matching the destination of a slash-only redirect.
      source: `/(${escapeRegex(rulePath(rule.sourcePath).slice(1))}$)`,
      destination: rulePath(rule.targetRoute).replace(/[:*+()$]/g, encodeCharacter),
      statusCode: 301
    }))
  }, null, 2)}\n`;
}

/** An nginx snippet for the server block that serves the new site. */
export function renderNginxRedirects(project: MigrationProject): string {
  const rules = safeRedirectRules(project.routes.redirects);
  return [
    ...ruleHeader(rules),
    "# Include this file inside the server block that serves the new site.",
    "# Match the original request URI to preserve encoded and repeated slashes.",
    ...rules.map((rule) =>
      `if ($request_uri ~ ${quoteConfig(`^${escapeRegex(rulePath(rule.sourcePath))}(?:[?].*)?$`)}) {\n  return 301 ${quoteConfig(`${rulePath(rule.targetRoute).replace(/\$/g, encodeCharacter)}$is_args$args`)};\n}`
    )
  ].join("\n") + "\n";
}

/** Apache rules for a `.htaccess` file or the main configuration. */
export function renderApacheRedirects(project: MigrationProject): string {
  const rules = safeRedirectRules(project.routes.redirects);
  return [
    ...ruleHeader(rules),
    "# Drop this file in the document root that serves the new site, or copy",
    "# the rules into the existing configuration. mod_rewrite is required.",
    "# Match the original request so encoded and repeated slashes stay distinct.",
    "# Encoded slashes require AllowEncodedSlashes NoDecode in the server config.",
    "RewriteEngine On",
    ...rules.map((rule) =>
      `RewriteCond %{THE_REQUEST} "^[^\\s]+\\s${escapeRegex(rulePath(rule.sourcePath))}(?:[?][^\\s]*)?\\s"\n` +
      `RewriteRule ^ "${rulePath(rule.targetRoute).replace(/\$/g, encodeCharacter).replace(/%/g, "\\%")}" [R=301,L,NE]`
    )
  ].join("\n") + "\n";
}

function ruleHeader(rules: readonly RedirectEntry[]): string[] {
  const count = `${rules.length} ${rules.length === 1 ? "rule" : "rules"}`;
  return [
    `# Generated by wp-migrate-core ${packageVersion} from the WordPress export.`,
    `# ${count}, matching the redirect map in migration/redirects.json.`,
    "# Review every rule against the live site before publishing; nothing was published for you."
  ];
}

/**
 * Rules are only usable when both paths are rooted, so a path that is not a
 * path is dropped here rather than written into a host configuration.
 */
function safeRedirectRules(redirects: readonly RedirectEntry[]): RedirectEntry[] {
  return redirects.filter(
    (redirect) => isLocalPath(redirect.sourcePath) && isLocalPath(redirect.targetRoute) && redirect.sourcePath !== redirect.targetRoute
  );
}

function isLocalPath(path: string): boolean {
  return path.startsWith("/") && !/^[\/\\]{2}|[?#\u0000-\u001f\u007f]/.test(path);
}

function slashOnly(rule: RedirectEntry): boolean {
  return rule.sourcePath.replace(/\/+$/, "") === rule.targetRoute.replace(/\/+$/, "");
}

function netlifyPath(path: string): string {
  return rulePath(path).replace(/[:*]/g, encodeCharacter);
}

/**
 * Percent-encode everything a rules file cannot carry literally, including
 * spaces, quotes, `#`, `?` and backslashes. Existing escapes are preserved,
 * and a stray percent sign is encoded so no rule contains a broken escape.
 */
function rulePath(path: string): string {
  return path
    .replace(/%(?![0-9A-Fa-f]{2})/g, "%25")
    .replace(/[^A-Za-z0-9\-._~/:@%!$&'()*+,;=]/gu, encodeCharacter);
}

function encodeCharacter(character: string): string {
  return [...new TextEncoder().encode(character)]
    .map((byte) => `%${byte.toString(16).toUpperCase().padStart(2, "0")}`)
    .join("");
}

/** Both nginx and Apache conditions use regular expressions. */
function escapeRegex(path: string): string {
  return path.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function quoteConfig(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\r/g, "\\r")}"`;
}
